language: node_js
node_js:
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
- '14'
sudo: false
deploy:
  provider: npm
  email: juerg.hunziker@gmail.com
  api_key:
    secure: b5AfrRecy+ugRr4szU9XOShb5pgjT/bHp1OzVwsrVHHxSjdI7KPlLIC9LNJm9fQK7hrelessyOIFdPtJiFuwpqiACYNfokLZeFh5k8+zeKe1Awj+0WovC12Gm+uFP135T0XrSZIykjGT+PvRu/oJJ5MykUhDt4uEafNh4YzLxA4=
  on:
    tags: true
    all_branches: true
    node: '10'
